service: coupon-book-api
frameworkVersion: '3'

plugins:
  - serverless-dotenv-plugin

custom:
  dotenv:
    include:
      - DB_HOST
      - DB_PORT
      - DB_USER
      - DB_PASS
      - DB_NAME

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: prod

  # <-- add this:
  httpApi:
    cors:
      allowedOrigins:
        - '*'                       # or restrict to your frontend domain
      allowedHeaders:
        - '*'                       # or list headers you use
      allowedMethods:
        - OPTIONS
        - GET
        - POST
        - PUT
        - DELETE

  environment:
    DB_HOST: ${env:DB_HOST}
    DB_PORT: ${env:DB_PORT}
    DB_USER: ${env:DB_USER}
    DB_PASS: ${env:DB_PASS}
    DB_NAME: ${env:DB_NAME}

functions:
  api:
    handler: lambda.handler      # matches module.exports.handler in lambda.js
    events:
      - httpApi:
          path: /{proxy+}
          method: ANY
